version: "3.5"

services:
  eos:
    image: eosio/eos:latest
    command: /opt/eosio/bin/nodeosd.sh -e --genesis-json /opt/eosio/bin/data-dir/genesis.json
    hostname: nodeosd
    ports:
      - "8888"
      - "9876"
    volumes:
      - nodeos-data-volume:/opt/eosio/bin/data-dir
      - ./config.ini:/opt/eosio/bin/data-dir/config.ini
      - ./genesis.json:/opt/eosio/bin/data-dir/genesis.json
    tmpfs:
      - /run
      - /tmp
volumes:
  nodeos-data-volume:

